version: '3.9'
services:
  front-end-astro:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SECRET_PASSWORD: password123
    restart: always
    container_name: front-end-astro
    ports:
      - 3001:3000